### PR TITLE
Fix deprecation warnings in nvim 0.10

### PR DESCRIPTION
**Pull request by aarondill**
This fixes several deprecation warnings in nvim 0.10.
It should still work in previous versions.
- **fix: vim.lsp.buf_get_clients is deprecated**
- **fix: vim.loop is deprecated**
- **fix: vim.api.nvim_buf_get_option is deprecated**

### CODE REVIEW

**Comment by amirbilu** [comment]
@aarondill thanks for the contribution. Was it tested on previous versions?

**Comment by aarondill** [comment]
I've tested everything except for the chat changes (which should still work) on `NVIM v0.9.5` built from source, as well as `NVIM v0.11.0-dev-49+g10601ac5f` (latest HEAD).
I don't use the chat, and I don't want to go through the trouble of making it work on my machine. If you'd like to test it, feel free, but vim.bo has existed since at least `NVIM v0.5.0` (see https://github.com/neovim/neovim/commit/43956dea55a49a847a0f2e5d9e0f48384cb34635 where it is already included in the docs).

Obviously the change in the readme is not backwards compatible, so older users still need to change it back to `vim.loop`. I can add a note if you'd like, but I think it's fine with `vim.uv`

**Comment by amirbilu** [comment]
Can you elaborate on needed in readme? Not sure I got this point

**Comment by aarondill** [comment]
@amirbilu In the README, I changed the reference to `vim.loop.os_uname()` to `vim.uv.os_uname()` for the "platform dependant build script". If one were to copy that code and use it before nvim 0.10.0, it would error.
If you want, I can add a note in the readme saying this and telling anyone running pre-0.10 to replace `vim.uv` with `vim.loop`

**Comment by amirbilu** [comment]
Got you

**Comment by aarondill** [comment]
@amirbilu I added the note to the readme

**Pull request merged**
