### PR TITLE
add a dummy property to the state request to avoid its conversion to an empty array

### PR DESCRIPTION
**Pull request by aarondill**
see https://github.com/codota/tabnine-nvim/issues/65#issuecomment-1516969490

### CODE REVIEW

**Comment by aarondill** [comment]
For future usage of `vim.json`, perhaps we should create our own instance, so that we can set the configuration we need without worrying about compatibility (or other plugins changing settings from under us). 
[Here's](https://github.com/neovim/neovim/blob/124bf818e2719d9d87f0671d203d159430e368a2/runtime/doc/lua.txt#L749) my own documentation of `vim.json.new()`, (I created a PR [here](https://github.com/neovim/neovim/pull/23229)). We could create a `tabnine.json` module (or just keep it in `state`) and use our own instance instead of the global instance.

**Comment by aarondill** [comment]
> 

If you decide you'd like to go down this path, let me know, I'd be more than happy to throw together a PR. *Should* be relatively simple (knock on wood)

**Review by amirbilu — APPROVED** [review]

**Comment by aarondill** [comment]
> For future usage of `vim.json`, perhaps we should create our own instance, so that we can set the configuration we need without worrying about compatibility (or other plugins changing settings from under us). [Here's](https://github.com/neovim/neovim/blob/124bf818e2719d9d87f0671d203d159430e368a2/runtime/doc/lua.txt#L749) my own documentation of `vim.json.new()`, (I created a PR [here](https://github.com/neovim/neovim/pull/23229)). We could create a `tabnine.json` module (or just keep it in `state`) and use our own instance instead of the global instance.

@amirbilu did you see this comment?

**Comment by amirbilu** [comment]
> > For future usage of `vim.json`, perhaps we should create our own instance, so that we can set the configuration we need without worrying about compatibility (or other plugins changing settings from under us). [Here's](https://github.com/neovim/neovim/blob/124bf818e2719d9d87f0671d203d159430e368a2/runtime/doc/lua.txt#L749) my own documentation of `vim.json.new()`, (I created a PR [here](https://github.com/neovim/neovim/pull/23229)). We could create a `tabnine.json` module (or just keep it in `state`) and use our own instance instead of the global instance.
> 
> @amirbilu did you see this comment?

Actually not sure. How other plugins handle this?

**Comment by aarondill** [comment]
> > > For future usage of `vim.json`, perhaps we should create our own instance, so that we can set the configuration we need without worrying about compatibility (or other plugins changing settings from under us). [Here's](https://github.com/neovim/neovim/blob/124bf818e2719d9d87f0671d203d159430e368a2/runtime/doc/lua.txt#L749) my own documentation of `vim.json.new()`, (I created a PR [here](https://github.com/neovim/neovim/pull/23229)). We could create a `tabnine.json` module (or just keep it in `state`) and use our own instance instead of the global instance.
> > 
> > 
> > @amirbilu did you see this comment?
> 
> Actually not sure. How other plugins handle this?

AFAIK, most of them don't use these methods because they have no documentation

**Comment by aarondill** [comment]
> 

`vim.json` is much faster than `vim.fn.json_*` because you avoid the vimscript conversion (both ways). The documentation for `vim.json` is provided at [openresty/lua-cjson](github.com/openresty/lua-cjson) (which is the internal provider for vim.json), but is not present in nvim's documentation, so it's hard to find.

**Comment by amirbilu** [comment]
So other plugins use their own implementation?

**Comment by aarondill** [comment]
There are exactly *0* mentions of `vim.json.new` on [github](https://github.com/search?q=vim.json.new&type=code), but 298 mentions of `vim.json.encode` on [github](https://github.com/search?q=vim.json.encode%28&type=code). (this test doesn't account for aliasing (IE `local json=vim.json`)

This method is *not* documented, so most plugins use the global `vim.json` assume that it's options will never change (which, without knowledge of the configuration methods, is a reasonable assumption).

**Comment by aarondill** [comment]
I have a PR at neovim/neovim#23229 to add documentation for these methods

**Comment by amirbilu** [comment]
Think I'm okay with leaving this as is for now

**Pull request merged**
