### PR TITLE
Clarify installation instructions

### PR DESCRIPTION
**Pull request by Flimm**
I'm still learning Neovim, and I don't already have `vimplug` or `packer`. The installation instructions were confusing for me. So I thought I would add some clarification.

### CODE REVIEW

**Comment by amirbilu** [comment]
Hi @Flimm thanks for that. What was most unclear? this is pretty common documentation convention

**Comment by amirbilu** [comment]
Closing this as stale. Feel free to reopen if you still think this is necessary.

**Comment by Flimm** [comment]
I've been using Neovim for a while, and Vim for around a decade, and I was confused by this. Now that I know the convention, it's very clear, but it wasn't clear to me at first. (I hadn't used at the time either vim-plug or packer, I was just used to using Vim 8+ native packages, which also work in Neovim.)
It wasn't clear to me if the code was Vimscript or Lua. It wasn't clear to me whether this was code that should be run once, or whether it should be added to `init.lua`, or `init.vim`, or both. It also wasn't clear to me that I still needed to run `:PlugInstall`.

**Comment by amirbilu** [comment]
@Flimm Thanks for the feedback. I've adjusted the `README`. Think it's better now?

**Comment by Flimm** [comment]
Fantastic! Much better than mine. I think this will help some fellow noobs (like me) out.

**Pull request closed without merging**
