### PR TITLE
Change windows build script and documentation

### PR DESCRIPTION
**Pull request by stefhol**
https://github.com/codota/tabnine-nvim/issues/38#issue-1634593259

1. Change Windows Build Script
2. Add information about execution policy 
3. Add an example for a function that gets plattform depended build script path

### CODE REVIEW

**Comment by stefhol** [comment]
I tested my changes on Windows and Macos

**Comment by amirbilu** [comment]
@instance-id can you take a look/approve this?

**Review by instance-id — APPROVED** [review]
I tested on Linux and Windows, things look good. I am ashamed I didn't think of simply omitting the parameter names in the powershell script like that to begin with. Passing the values using position instead of name elimites the discrepecy between the parameter names.

**Comment by amirbilu** [comment]
Thanks guys!
@stefhol drop us a message at support @tabnine.com to get Tabnine Pro credits

**Pull request merged**
