### PR TITLE
Change arch check in dl-binaries.ps1

### LINKED ISSUE #121: [BUG/DOCS] Build command for PowerShell doesn't work as described in README
The README suggests using the command `pwsh.exe -file .\dl_binaries.ps1` on windows, but the script doesn't appear to be compatible with powershell 6+ (pwsh-core). Resulting in the following error.

```
if ((Get-WmiObject win32_operatingsystem | Select-Object osarchitectu …
      ~~~~~~~~~~~~~
The term 'Get-WmiObject' is not recognized as a name of a cmdlet, function, script file, or executable program. Check the spelling of the name, or if a path was included, verify that the path is correct
and try again.
```

> Get-WmiObject have been deprecated in PowerShell Core. Please use CIM cmdlets.

The simplest solution is to change the README to use `powershell.exe`, otherwise the script should be updated.

### PR DESCRIPTION
**Pull request by aarondill**
Fixes #121
Note: I believe this was introduced *after* windows 7. I’m not certain though because Microsoft’s documentation seems to believe old versions won’t matter to anyone 🙄

### CODE REVIEW

**Comment by aarondill** [comment]
@daephx you seem to have functional pwsh v5 and v7, so could you please test that this works on your system?
Here’s a shortened version:
```
if (([Environment]::Is64BitOperatingSystem) {
Write-Output “64-bit”
}
else {
Write-Output “32-bit”
}
```

**Comment by daephx** [comment]
@aarondill Both versions 5 and 7 output the expected `64-bit` 👍

**Comment by aarondill** [comment]
I'm glad to hear that!
@amirbilu if you're satisfied with this PR it should be ready to merge 😃

**Review by amirbilu — APPROVED** [review]

**Comment by amirbilu** [comment]
Highly appreciated guys

**Pull request merged**
