### PR TITLE
Add ability to iterate over tabnine results

### PR DESCRIPTION
**Pull request by alexmarucci**
Added prev and next keymap to iterate over the current results and update the suggestion accordingly.

### CODE REVIEW

**Comment by alexmarucci** [comment]
Hi @amirbilu,

I am trying out Tabnine and noticed this feature is missing on this plugin but not in the vscode extension.

I hope PRs are welcome!

**Comment by amirbilu** [comment]
Hi @alexmarucci 
Definitely welcome. Thanks for that!
I'll be able to go over this only next week. Appreciate it!

**Comment by amirbilu** [comment]
@alexmarucci 

As this behavior make things a bit complex and I believe there are more important things to address at the moment - I won't merge it for now - but I'm leaving this open for future discussions.

**Comment by amirbilu** [comment]
Hi @jacek-kurlit 
Possibly, depends on the demand. U find this useful?

**Comment by jacek-kurlit** [comment]
Hard to say since I don't have such option. I didn't have time to use it in intellij but I don't understand why other editors offers it while nvim don't.

**Comment by amirbilu** [comment]
Closing this as won't do for now

**Pull request closed without merging**
