### PR TITLE
Add Windows Compatibility

### PR DESCRIPTION
**Pull request by instance-id**
This commit is to add Windows capability. Below you can see some examples of it operating as expected. If any adjustments need to be made to it, definitely let me know. 

Insert mode suggestion overlay:

Spawned Process Information:

### CODE REVIEW

**Comment by amirbilu** [comment]
Thanks! been waiting for this. It'll take me few days to go over this.

**Comment by amirbilu** [comment]
Apologies on the delay.. It will take me few more days

**Comment by amirbilu** [comment]
See my response here https://github.com/instance-id/tabnine-nvim/pull/1/files

**Review by amirbilu — APPROVED** [review]

**Comment by amirbilu** [comment]
Thanks for being part of the community! please leave us a message at `support@tabnine.com` to get Tabnine Pro credits

**Comment by limitedeternity** [comment]
#14 can be closed

**Comment by amirbilu** [comment]
thanks

**Pull request merged**
