### PR TITLE
add formatting

### PR DESCRIPTION
**Pull request by aarondill**
chore: add formatting workflow and stylua.toml

These should ensure consitent formatting in the future.
Feel free to modify the stylua.toml to your liking. I tried to keep it consistent with our current style (especially the tab-based indention)

### CODE REVIEW

**Comment by aarondill** [comment]
This is an implementation of this: https://github.com/codota/tabnine-nvim/pull/131#issuecomment-1793815406

**Review by amirbilu — COMMENTED** [review]
This looks good. Do we really need both format and push and check on PR? Usually you pick one of them. No?

**Comment by aarondill** [comment]
My thought process was that having a check on PRs encourages (but doesn't require?) contributors to run a formatter on their changes code to get the green check, thusly reducing diff sizes.

If you don't like this idea, I can remove the PR check and leave only the format-on-push.

**Comment by amirbilu** [comment]
With most Tabnine repos we just perform format check upon PR

**Comment by aarondill** [comment]
> With most Tabnine repos we just perform format check upon PR

So, to be clear, you don't want the auto-formatting at all? Just a check on new PRs? Wouldn't it slightly defeat the purpose of having a format workflow if it is still delegated to the contributor in all cases?

Additionally, wouldn't that have the potential to create *further* merge conflicts, since if a formatting mistake makes it to master (through a direct commit), it would then have to be fixed in every PR following, until one is merged?

**Comment by amirbilu** [comment]
With other repos we only check, but make it a required workflow. Which
means you cannot merge if gou haven't applied formatting

**Review by amirbilu — APPROVED** [review]

**Comment by amirbilu** [comment]
Made this check mandatory

**Pull request merged**
